name: Jekyll site CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Set up Ruby 2.7 specifically
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    
    # Set permissions
    - name: Set permissions
      run: chmod -R 777 .
      
    # Install dependencies and build
    - name: Build the site
      run: |
        bundle install
        bundle exec jekyll build --future
    
    # Optional: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
